# Generated by Django 5.0.6 on 2024-05-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_images/')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('Available_subject', models.CharField(max_length=1000)),
                ('numOfSubject', models.IntegerField()),
                ('Courses_Available', models.CharField(max_length=1000)),
                ('numOfCourses', models.IntegerField()),
                ('skilled_instructors', models.CharField(max_length=1000)),
                ('numOfInstructors', models.IntegerField()),
                ('Happy_Students', models.CharField(max_length=1000)),
                ('numOfStudents', models.IntegerField()),
            ],
        ),
    ]
