# Generated by Django 5.0.6 on 2024-05-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_featurecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='instructors')),
                ('name', models.CharField(max_length=300)),
                ('course', models.CharField(max_length=700)),
                ('x', models.CharField(max_length=500)),
                ('facebook', models.CharField(max_length=500)),
                ('linkedin', models.CharField(max_length=500)),
                ('instagram', models.CharField(max_length=500)),
                ('youtube', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseCoure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='course/')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
    ]
