# Generated by Django 5.0.6 on 2024-05-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_instructors_releasecoure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReleaseCoure',
        ),
    ]
