# Generated by Django 5.0.6 on 2024-06-03 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_releasecoure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseCoure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='course/')),
                ('title', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instructors')),
            ],
        ),
    ]
