# Generated by Django 5.0.6 on 2024-06-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_releasecoure_rating_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releasecoure',
            old_name='title',
            new_name='name',
        ),
    ]
