# Generated by Django 5.0.6 on 2024-06-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_releasecoure_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasecoure',
            name='description2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
